### PR TITLE
Make KStream health result serializable (#1026)

### LINKED ISSUE #1026: Kafka Streams and Jackson Serialization results in CodecException when calling Health endpoint
### Expected Behavior

The health endpoint returns health status and health details

### Actual Behaviour

An exception: `Unexpected error occurred: Error encoding object [io.micronaut.management.health.indicator.DefaultHealthResult@69164ed1] to JSON: No serializable introspection present for type TaskId. Consider adding Serdeable. Serializable annotate to type TaskId. Alternatively if you are not in control of the project's source code, you can use @SerdeImport(TaskId.class) to enable serialization of this type.
io.micronaut.http.codec.CodecException: Error encoding object [io.micronaut.management.health.indicator.DefaultHealthResult@69164ed1] to JSON: No serializable introspection present for type TaskId. Consider adding Serdeable. Serializable annotate to type TaskId. Alternatively if you are not in control of the project's source code, you can use @SerdeImport(TaskId.class) to enable serialization of this type.
`

### Steps To Reproduce

1. Run `git clone git@github.com:JacksonFraser/health-demo.git && cd health-demo && ./gradlew run`
2. Open new terminal window
3. Run `curl http://localhost:8081/health`

### Environment Information

- Operating System: Ubuntu 22.04.4 LTS
- JDK: openjdk 17.0.7 2023-04-18 LTS

### Example Application

https://github.com/JacksonFraser/health-demo

### Version

4.0.4

### PR DESCRIPTION
**Pull request by tmellanxt**
## Summary
This pull request addresses issue #1026 by implementing a custom `Serde<TaskId>` to kafka-streams module. This avoid a serialization error when calling the `/health` endpoint, which throws in turn a:
```
No serializable introspection present for type TaskId. Consider adding Serdeable. Serializable annotate to type TaskId. Alternatively if you are not in control of the project's source code, you can use @SerdeImport(TaskId.class) to enable serialization of this type.
```

## Changes Made
- Added serde processor as `annotationProcessor`, and serde api as `compileOnly` to load in the annotation. 
- Created a class dedicated to adding annotation for external classes that need serialising as part of the health result

## Related Issues
- Fixes #1026

### CODE REVIEW

File: kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamHealthSerdes.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+
+import io.micronaut.serde.annotation.SerdeImport;
+import org.apache.kafka.streams.processor.TaskId;
+
+
+/**
+ * Additional Serdes for Kafka streams health types returned as part of the {@link io.micronaut.management.health.indicator.HealthResult}.
+ */
+@SerdeImport(TaskId.class)
+public class KafkaStreamHealthSerdes {
```
Comment (graemerocher) [inline kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamHealthSerdes.java]: thanks can you make this non-public and add `@Internal`?

**Review by graemerocher — CHANGES_REQUESTED** [review]

File: kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamHealthSerdes.java (hunk 1 above)
Comment (tmellanxt) [reply kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamHealthSerdes.java]: Good point, done

Comment (graemerocher) [reply kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamHealthSerdes.java]: thanks, a test would be good if possible

Comment (tmellanxt) [reply kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamHealthSerdes.java]: I had written one, but wasn't sure if it was too specific a test to use a `JsonMapper` to check if a `TaskId` is serializable. If you think its appropriate here I'll add it. 

The kafka-streams instances injected into the tests have 0 active or standby tasks which is why this was never caught. 

Lmk your thoughts on this. If you want the concrete test I'll add it

Comment (graemerocher) [reply kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamHealthSerdes.java]: just a check that the type is serialisable is fine

Comment (tmellanxt) [reply kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamHealthSerdes.java]: While testing I've realised that the `TaskId` isn't serializable out of the box with Jackson, and if it were it would yield:
```
"taskId": {
  "topicGroupId": 0,
  "partition": 0
}
```
but I'm not sure this is helpful as part of the health report however. 

The `TaskId` object has a custom `.toString()` which formats it in a readable manner. I think its more appropriate here.
```
"taskId": "0_0"
```

After all, the task id is meant to be an identifier, showing its component internal fields in this manner doesn't seem helpful. 

This would be the change, adding the `toString()`. I'd make it null safe of course
```
details.put("taskId", taskMetadata.taskId().toString());
```

Thoughts?

Comment (graemerocher) [reply kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamHealthSerdes.java]: sure, for that case you probably need to implement a `Serializer` and remove the `@SerdeImport`

Comment (tmellanxt) [reply kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamHealthSerdes.java]: Well I was just going to call `.toString()` on the task object that gets put into the `Map<String, Object>`. 

Or would you rather a custom Serializer to allow users to override the serializer if they want?

Comment (tmellanxt) [reply kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamHealthSerdes.java]: Went with the custom Serde

File: kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/serde/TaskIdSerde.java [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+import io.micronaut.serde.Decoder;
+import io.micronaut.serde.Encoder;
+import io.micronaut.serde.Serde;
+import jakarta.inject.Singleton;
+import org.apache.kafka.streams.processor.TaskId;
+
+import java.io.IOException;
+
+@Singleton
+public class TaskIdSerde implements Serde<TaskId> {
```
Comment (graemerocher) [inline kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/serde/TaskIdSerde.java]: please add some javadoc to the type. 

This can probably also be made `final`

**Review by graemerocher — CHANGES_REQUESTED** [review]

File: kafka-streams/build.gradle [hunk 3]
```diff
@@ -18,8 +18,10 @@ micronaut {
 }
 
 dependencies {
+    annotationProcessor mnSerde.micronaut.serde.processor
```
Comment (tmellanxt) [inline kafka-streams/build.gradle]: This is no longer needed

**Review by graemerocher — APPROVED** [review]

**Comment by graemerocher** [comment]
sorry would you mind rebasing and then I will merge

**Comment by tmellanxt** [comment]
> sorry would you mind rebasing and then I will merge

Rebased @graemerocher

**Comment by graemerocher** [comment]
Thanks for the contribution!
