### PR TITLE
Catch record deserialization exceptions that may happen while polling

### LINKED ISSUE #640: Messages not reprocessed by consumer when SerializationException occurs while producing message
### Expected Behavior

I am using a KafkaListener that sends transformed messages via `@SendTo` to another topic. I am using `OffsetStrategy.SEND_TO_TRANSACTION` as well as the error strategy `RETRY_ON_ERROR` and I configured the producer as a transactional one. When a `SerializationException` occurs (e.g. Schema Registry not available), I expect that the message is retried as also happens when other exceptions occur in the listener.

### Actual Behaviour

Without any further configuration, the message is skipped (default behaviour of DefaultKafkaListenerExceptionHandler) and the next message is processed. In case this succeeds, the offset is committed via the producer and the failed message is skipped without processing.

As stated above, the expected behaviour is that those errors are also triggering a retry as other consumer errors do as well. 

**Workaround for now:** I replaced the bean `DefaultKafkaListenerExceptionHandler` with a custom one that seeks to the current offset instead of seeking to the next offset. However, this does not respect the retry back off configuration from the ErrorStrategy since it is not available there.

### Steps To Reproduce

_No response_

### Environment Information

_No response_

### Example Application

_No response_

### Version

4.5.0

### PR DESCRIPTION
**Pull request by guillermocalvo**
Fixes #640

### CODE REVIEW

File: kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java [hunk 1]
```diff
@@ -458,7 +459,28 @@ private void createConsumerThreadPollLoop(final ExecutableMethod<?, ?> method,
...
+                        // Unless in batch mode, try to honor the configured error strategy
+                        try {
+                            consumerRecords = kafkaConsumer.poll(pollTimeout);
+                        } catch (RecordDeserializationException ex) {
+                            if (LOG.isTraceEnabled()) {
+                                LOG.trace("Kafka consumer [{}] failed to deserialize value while polling", logMethod(method), ex);
+                            }
+                            final TopicPartition tp = ex.topicPartition();
+                            // By default, seek past the record to continue consumption
+                            consumerState.kafkaConsumer.seek(tp, ex.offset() + 1);
```
[the remark this answers is not in the document]
Comment (jeremyg484) [reply kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java:474]: Ahh, right, I see what you mean. Makes sense. In that case I'd say this is good to go.

File: kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorStrategySpec.groovy [hunk 2]
```diff
@@ -70,6 +70,22 @@ class KafkaErrorStrategySpec extends AbstractEmbeddedServerSpec {
...
+        myClient.sendNumber(123)
+
+        RetryOnErrorDeserializationErrorConsumer myConsumer = context.getBean(RetryOnErrorDeserializationErrorConsumer)
+
+        then:"The message that threw the exception is eventually left behind"
+        conditions.eventually {
+            myConsumer.number == 123
+        }
+        and:"the retry error strategy is honored"
+        myConsumer.exceptionCount.get() == 2
```
Comment (sdelamo) [inline kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorStrategySpec.groovy:86]: should not this be 1 since there has been only one error when we sent once `Not an integer`?

Comment (guillermocalvo) [reply kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorStrategySpec.groovy:86]: Nope, there's been 2 errors:
- First exception is thrown the first time we try to deserialize the message.
- Then [the error strategy kicks in with `DEFAULT_RETRY_COUNT=1`](https://github.com/micronaut-projects/micronaut-kafka/pull/771/files/aa0d66fe89c9d208184cc47ac155f1c5bbfa76c5#diff-6b0f4620784fab078897bdfde65e1ce637a9d85668ceff6799b1739880c98fbeR321), so we try to deserialize it once more and the second exception is thrown.

All the exceptions are delivered to the handler.

**Review by sdelamo — APPROVED** [review]

**Review by jeremyg484 — APPROVED** [review]
