### PR TITLE
Change log level for Kafka offset commit errors when using CooperativeSticky assignment strategy

### LINKED ISSUE #1227: Change log level for Kafka offset commit errors when using CooperativeSticky assignment strategy
### Description:

Currently, in **micronaut-kafka**, the following callback always logs errors when committing offsets asynchronously fails:

```java
return (offsets, exception) -> {
    if (consumerBean instanceof OffsetCommitCallback occ) {
        occ.onComplete(offsets, exception);
    } else if (exception != null) {
        LOG.error("Error asynchronously committing Kafka offsets [{}]: {}", offsets, exception.getMessage(), exception);
    }
};
```

However, when using the [CooperativeSticky](https://www.confluent.io/blog/cooperative-rebalancing-in-kafka-streams-consumer-ksqldb/) assignment strategy, logging these errors at ERROR level may be unnecessary or misleading.

### Suggestion:

Modify the callback so that **LOG.error** is triggered only if the consumer’s assignment strategy is not CooperativeSticky.

Consider lowering the log level (e.g., to WARN or INFO) depending on what we agree on.

I am happy to create PR :)

### PR DESCRIPTION
**Pull request by graemerocher**
## Summary
- detect CooperativeSticky assignors from listener consumer properties
- lower offset commit failure logging from ERROR to WARN for cooperative rebalances
- add focused tests for assignor detection and default exception handler logging

Resolves #1227

### CODE REVIEW

**Comment by graemerocher** [comment]
@copilot resolve the merge conflicts in this pull request

**Comment by graemerocher** [comment]
@copilot apply changes based on the comments in [this thread](https://github.com/micronaut-projects/micronaut-kafka/pull/1312#pullrequestreview-4130429723)

**Comment by graemerocher** [comment]
@copilot resolve the merge conflicts in this pull request

**Comment by graemerocher** [comment]
@copilot resolve the merge conflicts in this pull request

File: kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerState.java [hunk 1]
```diff
@@ -600,15 +601,16 @@ private static void addDlqHeader(Headers headers, String name, @Nullable String
...
+        return new KafkaListenerException(message, e, consumerBean, kafkaConsumer, consumerRecords, consumerRecord, info.cooperativeStickyAssignmentStrategy);
     }
 
     private OffsetCommitCallback resolveCommitCallback() {
         return (offsets, exception) -> {
             if (consumerBean instanceof OffsetCommitCallback occ) {
                 occ.onComplete(offsets, exception);
             } else if (exception != null) {
-                LOG.error("Error asynchronously committing Kafka offsets [{}]: {}", offsets, exception.getMessage(), exception);
+                OffsetCommitExceptionLogger.log(LOG, info.cooperativeStickyAssignmentStrategy,
```
Comment (radovanradic) [inline kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerState.java:612]: This will change all logs to warn when info.cooperativeStickyAssignmentStrategy is true. Might want to check if exception is `CommitFailedException`

File: kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerState.java [hunk 2]
```diff
@@ -600,15 +601,16 @@ private static void addDlqHeader(Headers headers, String name, @Nullable String
     }
 
     private KafkaListenerException wrapExceptionInKafkaListenerException(String message, Throwable e, @Nullable ConsumerRecords<?, ?> consumerRecords, @Nullable ConsumerRecord<?, ?> consumerRecord) {
-        return new KafkaListenerException(message, e, consumerBean, kafkaConsumer, consumerRecords, consumerRecord);
+        return new KafkaListenerException(message, e, consumerBean, kafkaConsumer, consumerRecords, consumerRecord, info.cooperativeStickyAssignmentStrategy);
     }
 
     private OffsetCommitCallback resolveCommitCallback() {
```
Comment (radovanradic) [inline kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerState.java:607]: Commit callback failures through ConsumerStateSingle#resolveCommitCallback() are still logged as ERROR. Probably should apply the same conditional logging there as in ConsumerState?

File: kafka/src/main/java/io/micronaut/configuration/kafka/exceptions/OffsetCommitExceptionLogger.java [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+    private static final String COOPERATIVE_STICKY_ASSIGNOR_SIMPLE_NAME = CooperativeStickyAssignor.class.getSimpleName();
+
+    private OffsetCommitExceptionLogger() {
+    }
+
+    public static boolean isCooperativeStickyAssignor(@Nullable Object assignmentStrategy) {
+        if (assignmentStrategy == null) {
+            return false;
+        }
+        if (assignmentStrategy instanceof CharSequence value) {
```
Comment (radovanradic) [inline kafka/src/main/java/io/micronaut/configuration/kafka/exceptions/OffsetCommitExceptionLogger.java:43]: Is it correct to return `isCooperativeStickyAssignor` true if there is `CooperativeStickyAssignor` anywhere in the list like `RangeAssignor,CooperativeStickyAssignor`?

**Review by radovanradic — APPROVED** [review]
