### PR TITLE
Fix Kafka Streams health endpoint regression on Kafka 4.x

### LINKED ISSUE #1219: Kafka Streams Health endpoint regression on Kafka 4.X
> [!NOTE]
> I understand micronaut kafka is not on kafka managed version 4.X yet, but just to get ahead of it and let y'all know.
>
> Pulled out of https://github.com/micronaut-projects/micronaut-kafka/issues/1181 when there was no 3.9.1

### Expected Behavior

Health endpoint works on Kafka 4.X. 

### Actual Behaviour

If you have serialize inclusion to the following, the health endpoint fails when it did not before.
- `non_absent`
- `non_default`
- `non_null`
- `always`

These are ok
- `non_empty`

```yaml
jackson:
  serialization:
     serializationInclusion: non_absent
```

`FAIL_ON_EMPTY_BEANS: false` fixes or changing the inclusion method to something that works. With Fail on empty, it's just a `{}` which is maybe weird?

Image

Logs
```
{
{
  "@timestamp": "2025-08-15T16:22:38.402796035Z",
  "message": "Unexpected error occurred: Error encoding object [io.micronaut.management.health.indicator.DefaultHealthResult@dd2abb5] to JSON: No serializer found for class org.apache.kafka.streams.processor.TaskId and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.micronaut.management.health.indicator.DefaultHealthResult[\"details\"]->java.util.HashMap[\"kafkaStreams\"]->io.micronaut.management.health.indicator.DefaultHealthResult[\"details\"]->java.util.HashMap[\"integrated-ordering-worker\"]->io.micronaut.management.health.indicator.DefaultHealthResult[\"details\"]->java.util.HashMap[\"integrated-ordering-worker-18269f17-3ae9-42b9-9e4e-5a483077758f-StreamThread-1\"]->java.util.HashMap[\"activeTasks\"]->java.util.HashMap[\"taskId\"])",
  "logger_name": "i.m.http.server.RouteExecutor",
  "thread_name": "lettuce-nioEventLoop-7-8",
  "level": "ERROR",
  "stack_trace": "i.m.http.codec.CodecException: Error encoding object [io.micronaut.management.health.indicator.DefaultHealthResult@dd2abb5] to JSON: No serializer found for class org.apache.kafka.streams.processor.TaskId and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.micronaut.management.health.indicator.DefaultHealthResult[\"details\"]->java.util.HashMap[\"kafkaStreams\"]->io.micronaut.management.health.indicator.DefaultHealthResult[\"details\"]->java.util.HashMap[\"integrated-ordering-worker\"]->io.micronaut.management.health.indicator.DefaultHealthResult[\"details\"]->java.util.HashMap[\"integrated-ordering-worker-18269f17-3ae9-42b9-9e4e-5a483077758f-StreamThread-1\"]->java.util.HashMap[\"activeTasks\"]->java.util.HashMap[\"taskId\"])\n\tat i.m.h.n.body.NettyJsonHandler.write(NettyJsonHandler.java:144)\n\t... 59 frames excluded\n\tat,
```

## Setup

Created via the Micronaut Launch and Kafka Streams example in the docs with force upgrade to kotlin 4.0.0 and jackson databind.

## Example Info

Image

Breakpoin in `KafkaStreamsHealth.java` `buildDetails()`

Image

### Steps To Reproduce

I understand micronaut kafka is not on kafka managed version 4.X yet, but just to get ahead of it and let y'all know.

### Environment Information

- JDK version 17

### Example Application

_No response_

### Version

4.9.2

### PR DESCRIPTION
**Pull request by graemerocher**
## Summary
- stringify Kafka Streams task ids in health details so Kafka 4.x task metadata remains JSON-safe
- cover the regression with a focused task-metadata spec
- avoid adding a Jackson-specific test dependency to kafka-streams

## Verification
- ./gradlew :micronaut-kafka-streams:test --tests '*KafkaStreamsHealthTaskMetadataSpec'
- Docker-backed Kafka Streams specs were not run because Docker is unavailable in this environment

Resolves #1219

### CODE REVIEW

**Comment by graemerocher** [comment]
@copilot apply changes based on the comments in [this thread](https://github.com/micronaut-projects/micronaut-kafka/pull/1302#pullrequestreview-4121187294)

File: kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamsHealth.java [hunk 1]
```diff
@@ -217,19 +217,15 @@ private static String getDefaultStreamName(final KafkaStreams kafkaStreams) {
...
-            if (details.containsKey(METADATA_PARTITIONS)) {
-                @SuppressWarnings("unchecked")
-                List<String> partitionsInfo = (List<String>) details.get(METADATA_PARTITIONS);
-                partitionsInfo.addAll(addPartitionsInfo(taskMetadata));
-            } else {
-                details.put(METADATA_PARTITIONS, addPartitionsInfo(taskMetadata));
-            }
-        }
-        return details;
+    private static List<Map<String, Object>> taskDetails(Set<TaskMetadata> taskMetadataSet) {
```
Comment (radovanradic) [inline kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamsHealth.java:220]: This changes the health details structure for task metadata, maybe should be documented somwhere?
